// Code generated by data-stub. DO NOT EDIT.
// source: tableName [fileName]

var BaseModal = require('../modal')

var modal = {
  table: '',
  fields: {
    '': {
      type: String,
      name: '',
      comment: '',
    }
  }
}
module.exports = new BaseModal(modal)
