// Code generated by data-stub. DO NOT EDIT.
// source: tableName [fileName]

var BaseModal = require('../modal')

var modal = {
  table: 'tableName',
  fields: {
    'columnName': {
      type: String,
      name: 'columnName',
      comment: 'comment from db',
    }
  }
}
module.exports = new BaseModal(modal)
