// Code generated by data-stub. DO NOT EDIT.
// source: tableName [ fileName tableComment ]

var BaseModal = require('../modal')

var modal = {
  table: 'tableName',
  comment: 'tableComment',
  name: 'fileName',
  fields: {
    'columnName': {
      type: String,
      name: 'columnName',
      comment: 'comment from db',
    }
  }
}
module.exports = new BaseModal(modal)
