// Code generated by data-stub. DO NOT EDIT.
// source: tableName [ fileName tableComment ]

var BaseModel = require('../model')

var model = {
  table: 'tableName',
  comment: 'tableComment',
  name: 'fileName',
  fields: {
    'columnName': {
      type: String,
      name: 'columnName',
      comment: 'comment from db',
    }
  },
}
module.exports = new BaseModel(model)
